using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ExpressBus.Protocol.Sourcegen.SerializationGeneration;

// TODO: ensure correctness and rename
public class MessageTypeIdSource
{
    private readonly SourceProductionContext _context;
    private readonly SemanticModel _semanticModel;
    private byte _currentId;

    public MessageTypeIdSource(SourceProductionContext context, SemanticModel semanticModel, byte baseId)
    {
        _context = context;
        _semanticModel = semanticModel;
        _currentId = baseId;
    }

    private string Generate()
    {
        string result = $"public const byte MessageTypeId = {_currentId};";

        checked
        {
            _currentId++;
        }

        return result;
    }

    public void AddSource(TypeDeclarationSyntax subject)
    {
        var type = _semanticModel.GetDeclaredSymbol(subject) as INamedTypeSymbol
            ?? throw new InvalidOperationException("Could not find declared symbol for subject.");

        string ns = type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string partialDeclaration = DeclarationGeneration.GeneratePartial(subject);
        string messageTypeId = Generate();

        string content = $$"""
            // <auto-generated>
            // This code was generated by a tool.
            // The modifications you make to this file will be lost if you regenerate it.

            namespace {ns};

            {{partialDeclaration}}
            {
                {{messageTypeId}}
            }
            """;
        _context.AddSource($"{ns}.{type.Name}.g.cs", content);
    }
}
