using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ExpressBus.Protocol.Sourcegen.SharedDependencies;

namespace ExpressBus.Protocol.Sourcegen.SerializationGeneration;

// TODO: make this class generate source code and rename it accordingly
public class SerializationSource
{

    private readonly SourceProductionContext _context;
    private readonly SemanticModel _semanticModel;

    private static readonly string[] _lineSeparators = { "\r\n", "\r", "\n" };

    public SerializationSource(SourceProductionContext context, SemanticModel semanticModel)
    {
        _context = context;
        _semanticModel = semanticModel;
    }

    public void AddSource(TypeDeclarationSyntax target, IReadOnlyList<SerializablePropData> propData)
    {
        var type = _semanticModel.GetDeclaredSymbol(target) as INamedTypeSymbol
            ?? throw new InvalidOperationException("Could not find declared symbol for subject.");

        string className = type.Name;

        string ns = type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string partialDeclaration = DeclarationGeneration.GeneratePartial(target);
        string members = GenerateMembers(className, propData);
        string indentedMembers = Indent(members);

        string content = $$"""
            // <auto-generated>
            // This code was generated by a tool.
            // The modifications you make to this file will be lost if you regenerate it.

            namespace {ns};

            {{partialDeclaration}}
            {
                {{indentedMembers}}
            }
            """;
        _context.AddSource($"{ns}.{className}.Serialization.g.cs", content);
    }

    private string GenerateMembers(string className, IReadOnlyList<SerializablePropData> propData)
    {
        var sb = new StringBuilder();

        // Properties
        foreach (var prop in propData)
        {
            sb.AppendLine(Indent(PropGeneration.Generate(prop)));
        }
        sb.AppendLine();

        // Constructor
        sb.AppendLine(Indent(ConstructorGeneration.Generate(className, propData)));
        sb.AppendLine();

        // ByteCount
        sb.AppendLine(Indent(ByteCountGeneration.Generate(propData)));
        sb.AppendLine();

        // ToBytes
        sb.AppendLine(Indent(ToBytesGeneration.Generate(className, propData)));
        sb.AppendLine();

        // FromBytes
        sb.AppendLine(Indent(FromBytesGeneration.Generate(className, propData)));

        return sb.ToString().TrimEnd('\r', '\n');
    }

    private string Indent(string content)
    {
        if (string.IsNullOrEmpty(content)) return content;
        var sb = new StringBuilder();
        var lines = content.Split(_lineSeparators, StringSplitOptions.None);
        foreach (var line in lines)
        {
            sb.AppendLine("    " + line);
        }
        return sb.ToString().TrimEnd('\r', '\n');
    }
}
