using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ExpressBus.Protocol.Sourcegen.SerializationGeneration;

// TODO: ensure correctness and rename
public class TypeIdSource
{
    private readonly SourceProductionContext _context;
    private readonly SemanticModel _semanticModel;
    private byte _currentId;

    public TypeIdSource(SourceProductionContext context, SemanticModel semanticModel, byte baseId)
    {
        _context = context;
        _semanticModel = semanticModel;
        _currentId = baseId;
    }

    public void AddSource(TypeDeclarationSyntax target)
    {
        var type = _semanticModel.GetDeclaredSymbol(target) as INamedTypeSymbol
            ?? throw new InvalidOperationException("Could not find declared symbol for subject.");

        string ns = type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string partialDeclaration = DeclarationGeneration.GeneratePartial(target, new[] { "ExpressBus.Protocol.Sourcegen.SharedDependencies.IWithTypeId" });
        string typeId = GenerateTypeId();

        string content = $$"""
            // <auto-generated>
            // This code was generated by a tool.
            // The modifications you make to this file will be lost if you regenerate it.

            namespace {ns};

            {{partialDeclaration}}
            {
                {{typeId}}
            }
            """;
        _context.AddSource($"{ns}.{type.Name}.TypeId.g.cs", content);
    }

    private string GenerateTypeId()
    {
        string result = $"public static byte TypeId => {_currentId};";

        checked
        {
            _currentId++;
        }

        return result;
    }
}
