using System.Buffers.Binary;
using ExpressBus.Protocol.Bus;
using ExpressBus.Transfer;

namespace ExpressBus.Protocol;

/// <summary>
/// Client-side base class for handling incoming server notifications.
/// </summary>
/// <remarks>
/// <para>
/// Notifications are fire-and-forget messages pushed from the server to clients.
/// This class reads from a connection: the first byte is the MessageTypeIdentifier,
/// the next 4 bytes are a little-endian int32 message size, followed by the payload
/// which is deserialized into the appropriate typed notification. The result is
/// dispatched to the corresponding handler. No response is sent back — notifications
/// are inherently one-way.
/// </para>
/// <para>
/// This is the client-side counterpart to <see cref="INotificationSender"/>.
/// While <see cref="IClientMessenger"/> / <see cref="RequestHandlerBase"/> handle
/// the request/response cycle, <see cref="INotificationSender"/> /
/// <see cref="NotificationHandlerBase"/> handle the server-to-client push channel.
/// </para>
/// <para>
/// Allocated buffers are disposed after the notification is dispatched, ensuring
/// pool-backed memory is always returned to its source even if the handler throws.
/// </para>
/// </remarks>
public abstract class NotificationHandlerBase
{
    private readonly IConnection _connection;

    protected NotificationHandlerBase(IConnection connection)
    {
        _connection = connection;
    }

    /// <summary>
    /// Allocates a buffer of the specified size for incoming notification payloads.
    /// </summary>
    /// <remarks>
    /// Implement this method to control the memory allocation strategy — for example,
    /// rent from <see cref="MemoryPool{T}.Shared"/> for pooled reuse, or allocate fresh memory.
    /// The returned <see cref="DisposableMemory"/> wraps the underlying owner and exposes
    /// a bounded view of exactly <paramref name="size"/> bytes. The base class disposes
    /// the returned <see cref="DisposableMemory"/> after processing the notification.
    /// </remarks>
    /// <param name="size">
    /// The exact byte length required for the buffer.
    /// </param>
    /// <returns>
    /// A <see cref="DisposableMemory"/> wrapping the allocated buffer, bounded to
    /// <paramref name="size"/> bytes.
    /// </returns>
    protected abstract DisposableMemory CreateBuffer(int size);

    /// <summary>
    /// Reads a notification from the associated connection, deserializes it, and dispatches it to the
    /// appropriate handler. Notifications are fire-and-forget — no response is sent back.
    /// </summary>
    /// <param name="cancellationToken">Optional cancellation token to abort the receive operations.</param>
    public async Task HandleNotificationAsync(CancellationToken cancellationToken = default)
    {
        // Read 1 byte: MessageTypeIdentifier
        var typeBuffer = CreateBuffer(1);
        await _connection.ReceiveFullAsync(typeBuffer.Memory, cancellationToken).ConfigureAwait(false);
        var typeByte = typeBuffer.Memory.Span[0];
        typeBuffer.Dispose();

        // Read 4 bytes: message size (little-endian int32)
        var sizeBuffer = CreateBuffer(4);
        await _connection.ReceiveFullAsync(sizeBuffer.Memory, cancellationToken).ConfigureAwait(false);
        var messageSize = BinaryPrimitives.ReadInt32LittleEndian(sizeBuffer.Memory.Span);
        sizeBuffer.Dispose();

        // Allocate buffer, read payload, deserialize
        var payload = CreateBuffer(messageSize);
        await _connection.ReceiveFullAsync(payload.Memory, cancellationToken).ConfigureAwait(false);
        var notificationBytes = payload.Memory;

        // Dispatch by MessageTypeIdentifier using if/else chain.
        // MessageTypeIdentifier is a static member generated by the Roslyn source generator —
        // not a compile-time constant from the compiler's perspective, so switch expression
        // cannot guarantee exhaustiveness (CS8509).
        if (typeByte == EventNotification.MessageTypeIdentifier)
            await HandleEventNotificationAsync(EventNotification.FromBytes(payload.Memory)).ConfigureAwait(false);
        else
            throw new FormatException($"Unknown MessageTypeIdentifier: 0x{typeByte:X2}");
    }

    /// <summary>
    /// Handles an event notification from the server.
    /// </summary>
    /// <remarks>
    /// Override this method in a derived class to process incoming event notifications.
    /// The notification payload has already been deserialized.
    /// </remarks>
    protected abstract Task HandleEventNotificationAsync(EventNotification notification);
}
