using System.Buffers.Binary;
using ExpressBus.Protocol.Bus;

namespace ExpressBus.Protocol;

/// <summary>
/// Client-side base class for handling incoming server notifications.
/// </summary>
/// <remarks>
/// <para>
/// Notifications are fire-and-forget messages pushed from the server to clients.
/// This class reads from an async stream: the first byte is the MessageTypeIdentifier,
/// the next 4 bytes are a little-endian int32 message size, followed by the payload
/// which is deserialized into the appropriate typed notification. The result is
/// dispatched to the corresponding handler.
/// </para>
/// <para>
/// This is the client-side counterpart to <see cref="INotificationSender"/>.
/// While <see cref="IRequestSender"/> / <see cref="RequestHandlerBase"/> handle
/// the request/response cycle, <see cref="INotificationSender"/> /
/// <see cref="NotificationHandlerBase"/> handle the server-to-client push channel.
/// </para>
/// <para>
/// Allocated buffers are wrapped in <see cref="DisposableMemory"/> and disposed
/// after the notification is dispatched, ensuring pool-backed memory is always returned
/// to its source even if the handler throws.
/// </para>
/// </remarks>
public abstract class NotificationHandlerBase
{
    /// <summary>
    /// Allocates a buffer of the specified size for incoming notification payloads.
    /// </summary>
    /// <remarks>
    /// Implement this method to control the memory allocation strategy — for example,
    /// rent from an <see cref="ArrayPool{T}"/> for pooled reuse, or allocate fresh memory.
    /// The returned <see cref="IMemoryOwner{T}"/> must have <c>Memory.Length</c> exactly
    /// equal to <paramref name="size"/>; a mismatch is rejected by <see cref="HandleNotificationAsync"/>.
    /// The caller is responsible for disposing the returned owner once the bytes have been processed.
    /// </remarks>
    /// <param name="size">
    /// The exact byte length required for the buffer.
    /// </param>
    /// <returns>
    /// An <see cref="IMemoryOwner{T}"/> whose <see cref="Memory{T}.Length"/> is exactly
    /// <paramref name="size"/>.
    /// </returns>
    protected abstract IMemoryOwner<byte> CreateBuffer(int size);

    /// <summary>
    /// Dispatches a serialized notification read from a stream to the appropriate handler.
    /// </summary>
    /// <param name="stream">
    /// The incoming notification stream. The first byte is the MessageTypeIdentifier, the next
    /// 4 bytes are a little-endian int32 representing the notification payload size, followed by
    /// the payload bytes.
    /// </param>
    public async Task HandleNotificationAsync(Stream stream)
    {
        // Read 1 byte: MessageTypeIdentifier
        var typeByte = await ByteTools.ReadSingleByteAsync(stream).ConfigureAwait(false);

        // Read 4 bytes: message size (little-endian int32)
        var sizeBuffer = new byte[4];
        await ByteTools.ReadExactlyAsync(stream, sizeBuffer).ConfigureAwait(false);
        var messageSize = BinaryPrimitives.ReadInt32LittleEndian(sizeBuffer);

        // Allocate buffer, read payload, deserialize
        var payload = CreateBuffer(messageSize);
        await ByteTools.ReadExactlyAsync(stream, payload.Memory).ConfigureAwait(false);
        var notificationBytes = payload.Memory;

        // Dispatch by MessageTypeIdentifier using if/else chain.
        // MessageTypeIdentifier is a static member generated by the Roslyn source generator —
        // not a compile-time constant from the compiler's perspective, so switch expression
        // cannot guarantee exhaustiveness (CS8509).
        if (typeByte == EventNotification.MessageTypeIdentifier)
            await HandleEventNotificationAsync(EventNotification.FromBytes(notificationBytes)).ConfigureAwait(false);
        else
            throw new FormatException($"Unknown MessageTypeIdentifier: 0x{typeByte:X2}");
    }

    /// <summary>
    /// Handles an event notification from the server.
    /// </summary>
    /// <remarks>
    /// Override this method in a derived class to process incoming event notifications.
    /// The notification payload has already been deserialized.
    /// </remarks>
    protected abstract Task HandleEventNotificationAsync(EventNotification notification);
}
