using System.Buffers.Binary;
using ExpressBus.Protocol.Bus;
using ExpressBus.Transfer;

namespace ExpressBus.Protocol;

/// <summary>
/// Client-side base class for handling incoming server notifications.
/// </summary>
/// <remarks>
/// <para>
/// Notifications are fire-and-forget messages pushed from the server to clients.
/// This class reads from a connection: the first byte is the MessageTypeIdentifier,
/// the next 4 bytes are a little-endian int32 message size, followed by the payload
/// which is deserialized into the appropriate typed notification. The result is
/// dispatched to the corresponding handler. No response is sent back — notifications
/// are inherently one-way.
/// </para>
/// <para>
/// This is the client-side counterpart to <see cref="INotificationSender"/>.
/// While <see cref="IRequestSender"/> / <see cref="RequestHandlerBase"/> handle
/// the request/response cycle, <see cref="INotificationSender"/> /
/// <see cref="NotificationHandlerBase"/> handle the server-to-client push channel.
/// </para>
/// <para>
/// Allocated buffers are disposed after the notification is dispatched, ensuring
/// pool-backed memory is always returned to its source even if the handler throws.
/// </para>
/// </remarks>
public abstract class NotificationHandlerBase
{
    /// <summary>
    /// Allocates a buffer of the specified size for incoming notification payloads.
    /// </summary>
    /// <remarks>
    /// Implement this method to control the memory allocation strategy — for example,
    /// rent from an <see cref="ArrayPool{T}"/> for pooled reuse, or allocate fresh memory.
    /// The returned <see cref="IMemoryOwner{T}"/> must have <c>Memory.Length</c> exactly
    /// equal to <paramref name="size"/>; a mismatch is rejected by <see cref="HandleNotificationAsync"/>.
    /// The base class disposes the returned owner after processing the notification.
    /// </remarks>
    /// <param name="size">
    /// The exact byte length required for the buffer.
    /// </param>
    /// <returns>
    /// An <see cref="IMemoryOwner{T}"/> whose <see cref="Memory{T}.Length"/> is exactly
    /// <paramref name="size"/>.
    /// </returns>
    protected abstract IMemoryOwner<byte> CreateBuffer(int size);

    /// <summary>
    /// Reads a notification from a connection, deserializes it, and dispatches it to the
    /// appropriate handler. Notifications are fire-and-forget — no response is sent back.
    /// </summary>
    /// <param name="connection">
    /// The connection to read from. The first byte is the MessageTypeIdentifier, the next
    /// 4 bytes are a little-endian int32 representing the notification payload size, followed by
    /// the payload bytes.
    /// </param>
    public async Task HandleNotificationAsync(IConnection connection)
    {
        // Read 1 byte: MessageTypeIdentifier
        var typeBuffer = CreateBuffer(1);
        await connection.ReceiveFullAsync(typeBuffer.Memory).ConfigureAwait(false);
        var typeByte = typeBuffer.Memory.Span[0];
        typeBuffer.Dispose();

        // Read 4 bytes: message size (little-endian int32)
        var sizeBuffer = CreateBuffer(4);
        await connection.ReceiveFullAsync(sizeBuffer.Memory).ConfigureAwait(false);
        var messageSize = BinaryPrimitives.ReadInt32LittleEndian(sizeBuffer.Memory.Span);
        sizeBuffer.Dispose();

        // Allocate buffer, read payload, deserialize
        var payload = CreateBuffer(messageSize);
        await connection.ReceiveFullAsync(payload.Memory).ConfigureAwait(false);
        var notificationBytes = payload.Memory;

        // Dispatch by MessageTypeIdentifier using if/else chain.
        // MessageTypeIdentifier is a static member generated by the Roslyn source generator —
        // not a compile-time constant from the compiler's perspective, so switch expression
        // cannot guarantee exhaustiveness (CS8509).
        if (typeByte == EventNotification.MessageTypeIdentifier)
            await HandleEventNotificationAsync(EventNotification.FromBytes(notificationBytes)).ConfigureAwait(false);
        else
            throw new FormatException($"Unknown MessageTypeIdentifier: 0x{typeByte:X2}");
    }

    /// <summary>
    /// Handles an event notification from the server.
    /// </summary>
    /// <remarks>
    /// Override this method in a derived class to process incoming event notifications.
    /// The notification payload has already been deserialized.
    /// </remarks>
    protected abstract Task HandleEventNotificationAsync(EventNotification notification);
}
