using System.Buffers.Binary;
using ExpressBus.Protocol.Bus;
using ExpressBus.Transfer;

namespace ExpressBus.Protocol;

/// <summary>
/// Server-side base class for the ExpressBus messaging protocol.
/// </summary>
/// <remarks>
/// <para>
/// This is the server's endpoint for the protocol contract. A concrete subclass implements the
/// abstract <c>HandleXxxRequest</c> methods to define the business logic for every request type
/// the server recognizes. <c>HandleRequestAsync</c> reads from a connection, dispatches to the
/// appropriate handler, serializes the result, sends the serialized response back over the same
/// connection, and disposes all buffers. It returns <see langword="void"/> because all I/O is
/// performed internally.
/// </para>
/// <para>
/// <see cref="IClientMessenger"/> (in the same namespace) is the client-side counterpart — it
/// exposes the same set of operations as methods that accept typed requests and return typed
/// results. <see cref="INotificationSender"/> handles server-to-client fire-and-forget
/// notifications. Together these types enforce a single, bidirectional protocol.
/// </para>
/// </remarks>
public abstract class RequestHandlerBase
{
    protected readonly IConnection Connection;

    public RequestHandlerBase(IConnection connection)
    {
        Connection = connection;
    }

    /// <summary>
    /// Reads a single request from the associated connection, dispatches it to the appropriate handler,
    /// serializes the response, sends it back over the same connection, and disposes all buffers.
    /// </summary>
    /// <param name="cancellationToken">Optional cancellation token to abort the I/O operations.</param>
    public async Task HandleRequestAsync(CancellationToken cancellationToken = default)
    {
        // Read 1 byte: MessageTypeIdentifier
        var typeBuffer = CreateBuffer(1);
        await Connection.ReceiveFullAsync(typeBuffer.Memory, cancellationToken).ConfigureAwait(false);
        var typeByte = typeBuffer.Memory.Span[0];
        typeBuffer.Dispose();

        // Read 4 bytes: message size (little-endian int32)
        var sizeBuffer = CreateBuffer(4);
        await Connection.ReceiveFullAsync(sizeBuffer.Memory, cancellationToken).ConfigureAwait(false);
        var messageSize = BinaryPrimitives.ReadInt32LittleEndian(sizeBuffer.Memory.Span);
        sizeBuffer.Dispose();

        // Allocate buffer, read payload, deserialize
        var payload = CreateBuffer(messageSize);
        await Connection.ReceiveFullAsync(payload.Memory, cancellationToken).ConfigureAwait(false);
        var requestBytes = payload.Memory;

        // Dispatch by MessageTypeIdentifier using if/else chain.
        // MessageTypeIdentifier is a static member generated by the Roslyn source generator —
        // not a compile-time constant from the compiler's perspective, so switch expression
        // cannot guarantee exhaustiveness (CS8509).
        DisposableMemory response;
        if (typeByte == BroadcastRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleBroadcastRequest(BroadcastRequest.FromBytes(requestBytes)));
        else if (typeByte == SubscribeRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleSubscribeRequest(SubscribeRequest.FromBytes(requestBytes)));
        else if (typeByte == UnsubscribeRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleUnsubscribeRequest(UnsubscribeRequest.FromBytes(requestBytes)));
        else if (typeByte == UnsubscribeAllRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleUnsubscribeAllRequest(UnsubscribeAllRequest.FromBytes(requestBytes)));
        else
            throw new FormatException($"Unknown MessageTypeIdentifier: 0x{typeByte:X2}");

        await Connection.SendAsync(response.Memory, cancellationToken);
        response.Dispose();
    }

    /// <summary>
    /// Repeatedly reads requests from the associated connection, dispatches each one,
    /// sends the response, and loops until <paramref name="cancellationToken"/> is triggered.
    /// </summary>
    /// <param name="cancellationToken">
    /// Triggered when the connection closes (via <see cref="IConnection.Closed"/>).
    /// Causes the loop to exit cleanly.
    /// </param>
    public async Task HandleRequestLoopAsync(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            await HandleRequestAsync(cancellationToken).ConfigureAwait(false);
        }
    }
    
    /// <summary>
    /// Allocates a buffer of the specified size for either incoming request payloads or
    /// outgoing response payloads.
    /// </summary>
    /// <remarks>
    /// Implement this method to control the memory allocation strategy — for example,
    /// rent from an <see cref="ArrayPool{T}"/> for pooled reuse, or allocate fresh memory.
    /// The returned <see cref="DisposableMemory"/> wraps the underlying owner and exposes
    /// a bounded view of exactly <paramref name="size"/> bytes. The base class disposes
    /// the returned <see cref="DisposableMemory"/> after transmitting the response bytes.
    /// </remarks>
    /// <param name="size">
    /// The exact byte length required for the buffer.
    /// </param>
    /// <returns>
    /// A <see cref="DisposableMemory"/> wrapping the allocated buffer, bounded to
    /// <paramref name="size"/> bytes.
    /// </returns>
    protected abstract DisposableMemory CreateBuffer(int size);

    private DisposableMemory SerializeResponse<T>(T response)
        where T : struct, IByteSerializable<T>, IMessageSize
    {
        var exactSize = response.ByteSize;
        var owner = CreateBuffer(exactSize);
        response.ToBytes(owner.Memory);
        return owner;
    }

    /// <summary>
    /// Handles a broadcast request.
    /// </summary>
    protected abstract BroadcastResponse HandleBroadcastRequest(BroadcastRequest request);

    /// <summary>
    /// Handles a subscribe request.
    /// </summary>
    protected abstract SubscribeResponse HandleSubscribeRequest(SubscribeRequest request);

    /// <summary>
    /// Handles an unsubscribe request.
    /// </summary>
    protected abstract UnsubscribeResponse HandleUnsubscribeRequest(UnsubscribeRequest request);

    /// <summary>
    /// Handles an unsubscribe-all request.
    /// </summary>
    protected abstract UnsubscribeAllResponse HandleUnsubscribeAllRequest(UnsubscribeAllRequest request);
}
