using System.Buffers.Binary;
using ExpressBus.Protocol.Bus;

namespace ExpressBus.Protocol;

/// <summary>
/// Server-side base class for the ExpressBus messaging protocol.
/// </summary>
/// <remarks>
/// <para>
/// This is the server's endpoint for the protocol contract. A concrete subclass implements the
/// abstract <c>HandleXxxRequest</c> methods to define the business logic for every request type
/// the server recognizes. <c>HandleRequestAsync</c> reads from an async stream: the first byte is
/// the MessageTypeIdentifier, the next 4 bytes are a little-endian int32 message size, followed
/// by the payload which is deserialized into the appropriate typed request. The result is
/// dispatched to the corresponding handler, serialized, and returned as bytes.
/// </para>
/// <para>
/// <see cref="IRequestSender"/> (in the same namespace) is the client-side counterpart — it
/// exposes the same set of operations as methods that accept typed requests and return typed
/// results. <see cref="INotificationSender"/> handles server-to-client fire-and-forget
/// notifications, while <see cref="NotificationHandlerBase"/> handles incoming notifications on
/// the client side. Together these types enforce a single, bidirectional protocol.
/// </para>
/// </remarks>
public abstract class RequestHandlerBase
{
    /// <summary>
    /// Allocates a buffer of the specified size for either incoming request payloads or
    /// outgoing response payloads.
    /// </summary>
    /// <remarks>
    /// Implement this method to control the memory allocation strategy — for example,
    /// rent from an <see cref="ArrayPool{T}"/> for pooled reuse, or allocate fresh memory.
    /// The returned <see cref="IMemoryOwner{T}"/> must have <c>Memory.Length</c> exactly
    /// equal to <paramref name="size"/>; a mismatch is rejected by <see cref="HandleRequestAsync"/>.
    /// The caller is responsible for disposing the returned owner once the bytes have been
    /// transmitted.
    /// </remarks>
    /// <param name="size">
    /// The exact byte length required for the buffer.
    /// </param>
    /// <returns>
    /// An <see cref="IMemoryOwner{T}"/> whose <see cref="Memory{T}.Length"/> is exactly
    /// <paramref name="size"/>.
    /// </returns>
    protected abstract IMemoryOwner<byte> CreateBuffer(int size);

    /// <summary>
    /// Dispatches a serialized request read from a stream to the appropriate handler
    /// and returns the serialized response.
    /// </summary>
    /// <param name="stream">
    /// The incoming request stream. The first byte is the MessageTypeIdentifier, the next
    /// 4 bytes are a little-endian int32 representing the message payload size, followed by
    /// the payload bytes.
    /// </param>
    /// <returns>
    /// A <see cref="DisposableMemory"/> containing the serialized response. The caller owns
    /// this wrapper and must dispose it after the response bytes have been transmitted.
    /// The underlying memory is returned to its pool on disposal.
    /// </returns>
    public async Task<DisposableMemory> HandleRequestAsync(Stream stream)
    {
        // Read 1 byte: MessageTypeIdentifier
        var typeByte = await ByteTools.ReadSingleByteAsync(stream).ConfigureAwait(false);

        // Read 4 bytes: message size (little-endian int32)
        var sizeBuffer = new byte[4];
        await ByteTools.ReadExactlyAsync(stream, sizeBuffer).ConfigureAwait(false);
        var messageSize = BinaryPrimitives.ReadInt32LittleEndian(sizeBuffer);

        // Allocate buffer, read payload, deserialize
        var payload = CreateBuffer(messageSize);
        await ByteTools.ReadExactlyAsync(stream, payload.Memory).ConfigureAwait(false);
        var requestBytes = payload.Memory;

        // Dispatch by MessageTypeIdentifier using if/else chain.
        // MessageTypeIdentifier is a static member generated by the Roslyn source generator —
        // not a compile-time constant from the compiler's perspective, so switch expression
        // cannot guarantee exhaustiveness (CS8509).
        DisposableMemory response;
        if (typeByte == BroadcastRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleBroadcastRequest(BroadcastRequest.FromBytes(requestBytes)));
        else if (typeByte == SubscribeRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleSubscribeRequest(SubscribeRequest.FromBytes(requestBytes)));
        else if (typeByte == UnsubscribeRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleUnsubscribeRequest(UnsubscribeRequest.FromBytes(requestBytes)));
        else if (typeByte == UnsubscribeAllRequest.MessageTypeIdentifier)
            response = SerializeResponse(HandleUnsubscribeAllRequest(UnsubscribeAllRequest.FromBytes(requestBytes)));
        else
            throw new FormatException($"Unknown MessageTypeIdentifier: 0x{typeByte:X2}");

        return response;
    }

    private DisposableMemory SerializeResponse<T>(T response)
        where T : struct, IByteSerializable<T>, IMessageSize
    {
        var exactSize = response.ByteSize;
        var owner = CreateBuffer(exactSize);
        response.ToBytes(owner.Memory);
        if (owner.Memory.Length != exactSize)
            throw new InvalidOperationException(
                $"CreateBuffer returned {owner.Memory.Length} bytes, expected {exactSize}.");
        return new DisposableMemory(owner, exactSize);
    }

    /// <summary>
    /// Handles a broadcast request.
    /// </summary>
    protected abstract BroadcastResponse HandleBroadcastRequest(BroadcastRequest request);

    /// <summary>
    /// Handles a subscribe request.
    /// </summary>
    protected abstract SubscribeResponse HandleSubscribeRequest(SubscribeRequest request);

    /// <summary>
    /// Handles an unsubscribe request.
    /// </summary>
    protected abstract UnsubscribeResponse HandleUnsubscribeRequest(UnsubscribeRequest request);

    /// <summary>
    /// Handles an unsubscribe-all request.
    /// </summary>
    protected abstract UnsubscribeAllResponse HandleUnsubscribeAllRequest(UnsubscribeAllRequest request);
}
