using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ExpressBus.Protocol.Sourcegen;

namespace ExpressBus.Protocol.Sourcegen.TypeIdGeneration;

public class TypeIdSource
{
    private readonly SourceProductionContext _context;
    private byte _currentId;

    public TypeIdSource(SourceProductionContext context, byte baseId)
    {
        _context = context;
        _currentId = baseId;
    }

    public void AddSource(NamedTypeMetadata target)
    {
        var type = target.Symbol;
        var syntax = target.Syntax;
        string ns = TypeNameResolution.GetNamespaceName(type.ContainingNamespace);
        string partialDeclaration = DeclarationGeneration.GeneratePartial(syntax, new[] { "ExpressBus.Protocol.Sourcegen.SharedDependencies.IWithTypeId" });
        string typeId = GenerateTypeId();

        string content = $$"""
            // <auto-generated>
            // This code was generated by a tool.
            // The modifications you make to this file will be lost if you regenerate it.
            // </auto-generated>

            namespace {{ns}};

            {{partialDeclaration}}
            {
                {{typeId}}
            }
            """;
        _context.AddSource($"{ns}.{type.Name}.TypeId.g.cs", content);
    }

    private string GenerateTypeId()
    {
        string result = $"public static byte TypeId => {_currentId};";

        checked
        {
            _currentId++;
        }

        return result;
    }
}
