using System.Text;

namespace ExpressBus.Protocol.SourceGeneration.Message;

/// <summary>
/// Generates the source text for all three protocol attribute classes.
/// </summary>
/// <remarks>
/// Emits:
/// <list type="bullet">
///   <item><description><c>[Message]</c> — triggers base message struct generation.</description></item>
///   <item><description><c>[GenerateSerialization]</c> — triggers serialization code generation.</description></item>
///   <item><description><c>[GenerateSerializedField]</c> — declares fields for serialization.</description></item>
/// </list>
/// </remarks>
internal static class AttributeGeneration
{
	private static readonly string[] GlobalUsings =
	[
		"global using global::System;",
		"global using global::ExpressBus.Protocol;",
	];

	/// <summary>
	/// Generates the source text for all three attribute classes.
	/// </summary>
	public static string GenerateAttributeClasses()
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		foreach (var usingDirective in GlobalUsings)
			sb.AppendLine(usingDirective);
		sb.AppendLine();
		sb.AppendLine("namespace ExpressBus.Protocol;");
		sb.AppendLine();
		sb.AppendLine(GenerateMessageAttribute());
		sb.AppendLine();
		sb.AppendLine(GenerateGenerateSerializationAttribute());
		sb.AppendLine();
		sb.AppendLine(GenerateGenerateSerializedFieldAttribute());
		return sb.ToString();
	}

	private static string GenerateMessageAttribute()
	{
		return """
			/// <summary>
			/// Marks a struct as a protocol message type.
			/// </summary>
			/// <remarks>
			/// Applying this attribute generates a partial struct declaration that
			/// implements <c>IByteSerializable&lt;T&gt;</c>, <c>IMessage</c>, and
			/// <c>IMessageSize</c>, along with <c>RequestId</c> and
			/// <c>MessageTypeIdentifier</c>. To add binary serialization members
			/// (<c>ByteSize</c>, <c>FromBytes</c>, <c>ToBytes</c>), also apply
			/// <c>[GenerateSerialization]</c>.
			/// </remarks>
			/// <param name="type">The message type identifier.</param>
			[System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
			public sealed class MessageAttribute(MessageType type = default) : System.Attribute
			{
				/// <summary>
				/// Gets the message type identifier.
				/// </summary>
				public MessageType Type { get; } = type;
			}
			""";
	}

	private static string GenerateGenerateSerializationAttribute()
	{
		return """
			/// <summary>
			/// Triggers source-generation of binary serialization members for a message struct.
			/// </summary>
			/// <remarks>
			/// Must be applied to a struct that also has <c>[Message]</c> attribute.
			/// When present, the source generator emits <c>ByteSize</c>, constructor,
			/// <c>FromBytes</c>, and <c>ToBytes</c> members, and the struct implements
			/// <c>IByteSerializable&lt;T&gt;</c> and <c>IMessageSize</c>.
			/// </remarks>
			/// <param name="type">The message type identifier used on the wire.</param>
			[System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
			public sealed class GenerateSerializationAttribute(MessageType type) : System.Attribute
			{
				/// <summary>
				/// Gets the message type identifier for this message.
				/// </summary>
				public MessageType Type { get; } = type;
			}
			""";
	}

	private static string GenerateGenerateSerializedFieldAttribute()
	{
		return """
			/// <summary>
			/// Marks a field for source-generated binary serialization.
			/// </summary>
			/// <remarks>
			/// Must be applied to a struct that also has <c>[GenerateSerialization]</c> attribute.
			/// The field type must be a primitive (<c>byte</c>, <c>bool</c>, <c>short</c>,
			/// <c>int</c>, <c>long</c>, <c>float</c>, <c>double</c>, <c>Guid</c>), or an
			/// enum whose underlying type is one of the above.
			/// </remarks>
			/// <param name="name">The field name as it will appear in the generated struct.</param>
			/// <param name="type">The serialized type (must be a primitive, Guid, or enum thereof).</param>
			[System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
			public sealed class GenerateSerializedFieldAttribute(string name, System.Type type) : System.Attribute
			{
				/// <summary>
				/// Gets the field name.
				/// </summary>
				public string Name { get; } = name;

				/// <summary>
				/// Gets the serialized type of the field.
				/// </summary>
				public System.Type Type { get; } = type;
			}
			""";
	}
}
