using Microsoft.CodeAnalysis;
using System.Buffers.Binary;
using System.Text;

namespace ExpressBus.Protocol.SourceGeneration.Message;

/// <summary>
/// Generates a partial struct for types annotated with <c>[Message]</c>.
/// </summary>
/// <remarks>
/// For each validated <c>[Message]</c> struct this produces:
/// <list type="bullet">
///   <item><description>A partial struct declaration with the appropriate interfaces.</description></item>
///   <item><description><c>MessageTypeIdentifier</c> — the unique byte tag assigned by the generator.</description></item>
/// </list>
/// <para>
/// For <c>[Message]</c>-only types, this class also generates
/// <c>ByteSize</c>, constructor, <c>FromBytes</c>, and <c>ToBytes</c>.
/// For types with <c>[GenerateSerialization]</c>, <c>SerializationGeneration</c>
/// generates those members instead.
/// </para>
/// </remarks>
internal static class MessageGeneration
{
	private static readonly string[] GlobalUsings =
	[
		"global using global::System;",
		"global using global::System.Buffers;",
		"global using global::System.Buffers.Binary;",
		"global using global::ExpressBus.Protocol;",
		"global using global::ExpressBus.Buffering;",
	];

	/// <summary>
	/// Generates a partial struct for a single <c>[Message]</c> type.
	/// </summary>
	/// <param name="symbol">The message struct symbol.</param>
	/// <param name="identifier">The sequential MessageTypeIdentifier (0..N).</param>
	/// <param name="compilation">The compilation for semantic analysis.</param>
	/// <param name="messageType">The MessageType enum value for the type.</param>
	/// <param name="isSerializationType">True if the type also has [GenerateSerialization] — additional members come from SerializationGeneration.</param>
	public static string GenerateMembersForSingleType(
		SyntaxSymbol symbol,
		byte identifier,
		Compilation compilation,
		MessageType messageType,
		bool isSerializationType)
	{
		var semanticModel = compilation.GetSemanticModel(symbol.Declaration.SyntaxTree);
		var props = SerializedPropResolver.ParseSerializedPropAttributes(symbol, semanticModel).ToList();
		var namespaceName = symbol.Symbol.ContainingNamespace.ToDisplayString();
		var typeName = symbol.Symbol.Name;

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		foreach (var usingDirective in GlobalUsings)
			sb.AppendLine(usingDirective);
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		if (!isSerializationType)
		{
			// [Message]-only type: generate everything including all interfaces.
			sb.AppendLine($"\tpublic partial struct {typeName} : IByteSerializable<{typeName}>, IMessage, IMessageSize");
			sb.AppendLine("\t{");

			// MessageTypeIdentifier — static for type-level dispatch.
			sb.AppendLine($"\tpublic static byte MessageTypeIdentifier => {identifier};");

			// ByteSize — 1 byte MessageTypeIdentifier + 4 bytes message size + property data.
			var constantPropSize = ComputeConstantPropSize(props);
			sb.AppendLine($"\tpublic int ByteSize => 5 + {constantPropSize};");

			GenerateConstructor(sb, typeName, props);
			GenerateFromBytesMethod(sb, typeName, props);
			GenerateToBytesMethod(sb, typeName, props);

			sb.AppendLine("\t}");
		}
		else
		{
			// [GenerateSerialization] type: only declare interfaces and MessageTypeIdentifier.
			// Serialization members come from SerializationGeneration.
			sb.AppendLine($"\tpublic partial struct {typeName} : IByteSerializable<{typeName}>, IMessage, IMessageSize");
			sb.AppendLine("\t{");

			// MessageTypeIdentifier — static for type-level dispatch.
			sb.AppendLine($"\tpublic static byte MessageTypeIdentifier => {identifier};");

			sb.AppendLine("\t}");
		}

		sb.AppendLine("}");

		return sb.ToString();
	}

	private static void GenerateConstructor(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props)
	{
		sb.AppendLine();
		var params_ = props.Select(p =>
		{
			var paramType = p.EnumType ?? p.UnderlyingType.CSharpTypeName();
			return $"{paramType} {ToCamelCase(p.Name)}";
		});
		sb.AppendLine($"\tpublic {typeName}({string.Join(", ", params_)})");
		sb.AppendLine("\t{");
		foreach (var prop in props)
		{
			var assignment = prop.EnumType is not null
				? $"({prop.EnumType}){ToCamelCase(prop.Name)}"
				: ToCamelCase(prop.Name);
			sb.AppendLine($"\t\t{prop.Name} = {assignment};");
		}
		sb.AppendLine("\t}");
	}

	private static void GenerateFromBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic static {typeName} FromBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");

		// Ensure buffer has at least 5 bytes for the frame (type ID + message size).
		sb.AppendLine("\t\tByteTools.EnsureLength(buffer.Span, 5, null);");

		// Read and validate the type identifier.
		sb.AppendLine("\t\tif (buffer.Span[0] != MessageTypeIdentifier)");
		sb.AppendLine("\t\t\tthrow new FormatException($\"Unexpected MessageTypeIdentifier: 0x{buffer.Span[0]:X2}. Expected 0x{MessageTypeIdentifier:X2}.\");");

		// Read the message size from the next 4 bytes.
		sb.AppendLine("\t\tvar messageSize = BinaryPrimitives.ReadInt32LittleEndian(buffer.Span.Slice(1));");

		// Ensure the buffer has enough bytes for the full message.
		sb.AppendLine("\t\tByteTools.EnsureLength(buffer.Span, messageSize, null);");

		// Read properties starting after the 5-byte frame.
		sb.AppendLine("\t\tvar reader = new ByteReader(buffer.Span.Slice(5));");
		sb.AppendLine();

		foreach (var prop in props)
		{
			var readMethod = prop.UnderlyingType.ReadMethodName();
			var paramName = ToCamelCase(prop.Name);
			var varType = prop.EnumType ?? prop.UnderlyingType.CSharpTypeName();
			var cast = prop.EnumType is not null ? $"({varType})" : "";
			sb.AppendLine($"\t\t{varType} {paramName} = {cast}reader.{readMethod}();");
		}

		sb.AppendLine();
		sb.AppendLine($"\t\treturn new {typeName}({string.Join(", ", props.Select(p => ToCamelCase(p.Name)))});");
		sb.AppendLine("\t}");
	}

	private static void GenerateToBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic ReadOnlyMemory<byte> ToBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");

		// Use this.ByteSize for the buffer check (instance-aware, not default).
		sb.AppendLine("\t\tByteTools.EnsureLength(buffer.Span, this.ByteSize);");
		sb.AppendLine("\t\tvar writer = new ByteWriter(buffer.Span);");

		// Write the frame: type identifier + message size.
		sb.AppendLine("\t\twriter.WriteByte(MessageTypeIdentifier);");
		sb.AppendLine("\t\twriter.WriteInt(this.ByteSize);");
		sb.AppendLine();

		foreach (var prop in props)
		{
			var writeMethod = prop.UnderlyingType.WriteMethodName();
			string cast = prop.EnumType is not null
				? $"({prop.UnderlyingType.CSharpTypeName()})"
				: "";
			sb.AppendLine($"\t\twriter.{writeMethod}({cast}{prop.Name});");
		}

		sb.AppendLine();
		sb.AppendLine("\t\treturn buffer;");
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Computes the total byte size of all properties (excluding the 5-byte frame).
	/// </summary>
	private static int ComputeConstantPropSize(IReadOnlyList<MessagePropInfo> props) =>
		props.Sum(p => p.UnderlyingType.ByteSize());

	private static string ToCamelCase(string name) =>
		char.ToLowerInvariant(name[0]) + name.Substring(1);
}
