using Microsoft.CodeAnalysis;
using System.Text;

namespace ExpressBus.Protocol.SourceGeneration.Message;

/// <summary>
/// Generates binary serialization members for message structs annotated with <c>[GenerateSerialization]</c>.
/// </summary>
/// <remarks>
/// For each validated <c>[GenerateSerialization]</c> struct this produces:
/// <list type="bullet">
///   <item><description><c>ByteSize</c> instance property — total serialized byte count.</description></item>
///   <item><description>Constructor — takes user fields.</description></item>
///   <item><description><c>FromBytes</c> — deserializes from a byte buffer.</description></item>
///   <item><description><c>ToBytes</c> — serializes into a byte buffer.</description></item>
/// </list>
/// <para>
/// The partial struct declaration (including <c>IMessage</c> and <c>MessageTypeIdentifier</c>)
/// is generated by <c>MessageGeneration</c>. This class only generates the serialization-specific members.
/// </para>
/// </remarks>
internal static class SerializationGeneration
{
	private static readonly string[] GlobalUsings =
	[
		"global using global::System;",
		"global using global::System.Buffers;",
		"global using global::ExpressBus.Protocol;",
		"global using global::ExpressBus.Buffering;",
	];

	/// <summary>
	/// Generates serialization members for a single serialization-enabled message type.
	/// </summary>
	/// <remarks>
	/// The partial struct declaration (interfaces, <c>MessageTypeIdentifier</c>)
	/// is generated by <c>MessageGeneration</c>. This method generates:
	/// user fields, <c>ByteSize</c>, constructor,
	/// <c>FromBytes</c>, and <c>ToBytes</c>.
	/// <para>
	/// For <c>[GenerateSerialization]</c> types, it complements <c>MessageGeneration</c>
	/// by adding serialization-specific members.
	/// </para>
	/// </remarks>
	public static string GenerateMembersForSingleType(
		SyntaxSymbol symbol,
		byte identifier,
		Compilation compilation,
		MessageType messageType)
	{
		var semanticModel = compilation.GetSemanticModel(symbol.Declaration.SyntaxTree);
		var fields = SerializedFieldResolver.ParseSerializedFieldAttributes(symbol, semanticModel).ToList();
		var namespaceName = symbol.Symbol.ContainingNamespace.ToDisplayString();
		var typeName = symbol.Symbol.Name;

		var hasMemoryFields = fields.Any(f => f.UnderlyingType.IsMemoryType());
		var constantFieldSize = ComputeConstantFieldSize(fields);

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		foreach (var usingDirective in GlobalUsings)
			sb.AppendLine(usingDirective);
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");
		sb.AppendLine($"\tpublic partial struct {typeName} : IByteSerializable<{typeName}>, IMessageSize");
		sb.AppendLine("\t{");

		// User fields — generated from [GenerateSerializedField] attributes.
		foreach (var field in fields)
			sb.AppendLine($"\t\tpublic readonly {GetFieldType(field)} {field.Name};");
		sb.AppendLine();

		// ByteSize — constant if no memory fields, runtime-computed otherwise.
		if (hasMemoryFields)
		{
			var constantSize = 1 + constantFieldSize;
			var memorySizes = string.Join(" + ", fields.Where(f => f.UnderlyingType.IsMemoryType())
				.Select(f => $"{f.Name}.ByteSize"));
			if (constantSize > 0)
				sb.AppendLine($"\tpublic int ByteSize => {constantSize} + {memorySizes};");
			else
				sb.AppendLine($"\tpublic int ByteSize => {memorySizes};");
		}
		else
		{
			sb.AppendLine($"\tpublic int ByteSize => 1 + {constantFieldSize};");
		}

		GenerateConstructor(sb, typeName, fields);
		GenerateFromBytesMethod(sb, typeName, fields, constantFieldSize, hasMemoryFields);
		GenerateToBytesMethod(sb, typeName, fields);

		sb.AppendLine("\t}");
		sb.AppendLine("}");

		return sb.ToString();
	}

	/// <summary>
	/// Computes the total byte size of all non-memory fields.
	/// </summary>
	private static int ComputeConstantFieldSize(IReadOnlyList<MessageFieldInfo> fields) =>
		fields.Where(f => !f.UnderlyingType.IsMemoryType())
			.Sum(f => f.UnderlyingType.ByteSize());

	/// <summary>
	/// Returns the C# type name for a field (enum FQN or primitive/memory type).
	/// </summary>
	private static string GetFieldType(MessageFieldInfo field) =>
		field.EnumType ?? field.UnderlyingType.CSharpTypeName();

	/// <summary>
	/// Generates the constructor with user-facing parameters.
	/// </summary>
	private static void GenerateConstructor(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessageFieldInfo> fields)
	{
		sb.AppendLine();
		var params_ = fields.Select(f => $"{GetFieldType(f)} {ToCamelCase(f.Name)}");
		sb.AppendLine($"\tpublic {typeName}({string.Join(", ", params_)})");
		sb.AppendLine("\t{");
		foreach (var field in fields)
		{
			var assignment = field.EnumType is not null
				? $"({field.EnumType}){ToCamelCase(field.Name)}"
				: ToCamelCase(field.Name);
			sb.AppendLine($"\t\t{field.Name} = {assignment};");
		}
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates the FromBytes deserialization method.
	/// </summary>
	private static void GenerateFromBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessageFieldInfo> fields,
		int constantFieldSize,
		bool hasMemoryFields)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic static {typeName} FromBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");

		// Validate buffer size before deserialization.
		var minConstantSize = 1 + constantFieldSize;
		if (hasMemoryFields)
		{
			if (minConstantSize > 1)
				sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, {minConstantSize}, null);");
		}
		else
		{
			sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, {minConstantSize});");
		}

		sb.AppendLine("\t\tvar reader = new ByteReader(buffer.Span.Slice(1));");
		sb.AppendLine();

		foreach (var field in fields)
		{
			if (field.UnderlyingType.IsMemoryType())
				GenerateMemoryFieldRead(sb, field);
			else
				GenerateNormalFieldRead(sb, field);
		}

		sb.AppendLine();
		sb.AppendLine($"\t\treturn new {typeName}({string.Join(", ", fields.Select(f => ToCamelCase(f.Name)))});");
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates serialization for a non-memory field in FromBytes.
	/// </summary>
	private static void GenerateNormalFieldRead(StringBuilder sb, MessageFieldInfo field)
	{
		var readMethod = field.UnderlyingType.ReadMethodName();
		var paramName = ToCamelCase(field.Name);
		var varType = GetFieldType(field);
		var cast = field.EnumType is not null ? $"({varType})" : "";
		sb.AppendLine($"\t\t{varType} {paramName} = {cast}reader.{readMethod}();");
	}

	/// <summary>
	/// Generates serialization for a memory field in FromBytes.
	/// </summary>
	private static void GenerateMemoryFieldRead(StringBuilder sb, MessageFieldInfo field)
	{
		var paramName = ToCamelCase(field.Name);
		var varType = GetFieldType(field);
		var itemSize = field.UnderlyingType.GetMemoryItemSize();

		sb.AppendLine($"\t\tvar {paramName}Count = reader.ReadInt();");
		sb.AppendLine($"\t\tvar {paramName}ItemSize = reader.ReadByte();");
		sb.AppendLine($"\t\tvar {paramName}Data = reader.ReadBytes({paramName}Count * {paramName}ItemSize).ToArray();");
		sb.AppendLine($"\t\t{varType} {paramName} = new({paramName}Count, {paramName}Data);");
	}

	/// <summary>
	/// Generates the ToBytes serialization method.
	/// </summary>
	private static void GenerateToBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessageFieldInfo> fields)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic ReadOnlyMemory<byte> ToBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");
		sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, ByteSize);");
		sb.AppendLine("\t\tvar writer = new ByteWriter(buffer.Span);");
		sb.AppendLine("\t\twriter.WriteByte(MessageTypeIdentifier);");
		sb.AppendLine();

		foreach (var field in fields)
		{
			if (field.UnderlyingType.IsMemoryType())
				GenerateMemoryFieldWrite(sb, field);
			else
				GenerateNormalFieldWrite(sb, field);
		}

		sb.AppendLine();
		sb.AppendLine("\t\treturn buffer;");
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates serialization for a non-memory field in ToBytes.
	/// </summary>
	private static void GenerateNormalFieldWrite(StringBuilder sb, MessageFieldInfo field)
	{
		var writeMethod = field.UnderlyingType.WriteMethodName();
		var cast = field.EnumType is not null
			? $"({field.UnderlyingType.CSharpTypeName()})"
			: "";
		sb.AppendLine($"\t\twriter.{writeMethod}({cast}{field.Name});");
	}

	/// <summary>
	/// Generates serialization for a memory field in ToBytes.
	/// </summary>
	private static void GenerateMemoryFieldWrite(StringBuilder sb, MessageFieldInfo field)
	{
		var fieldName = field.Name;
		sb.AppendLine($"\t\tvar {fieldName}Bytes = new byte[{fieldName}.ByteSize];");
		sb.AppendLine($"\t\t{fieldName}.ToBytes({fieldName}Bytes);");
		sb.AppendLine($"\t\twriter.WriteBytes({fieldName}Bytes);");
	}

	private static string ToCamelCase(string name) =>
		char.ToLowerInvariant(name[0]) + name.Substring(1);
}
