using Microsoft.CodeAnalysis;
using System.Text;

namespace ExpressBus.Protocol.SourceGeneration.Message;

/// <summary>
/// Generates binary serialization members for message structs annotated with <c>[GenerateSerialization]</c>.
/// </summary>
/// <remarks>
/// For each validated <c>[GenerateSerialization]</c> struct this produces:
/// <list type="bullet">
///   <item><description><c>ByteSize</c> instance property — total serialized byte count.</description></item>
///   <item><description>Constructor — takes user properties.</description></item>
///   <item><description><c>FromBytes</c> — deserializes from a byte buffer.</description></item>
///   <item><description><c>ToBytes</c> — serializes into a byte buffer.</description></item>
/// </list>
/// <para>
/// The partial struct declaration (including <c>IMessage</c> and <c>MessageTypeIdentifier</c>)
/// is generated by <c>MessageGeneration</c>. This class only generates the serialization-specific members.
/// </para>
/// </remarks>
internal static class SerializationGeneration
{
	private static readonly string[] GlobalUsings =
	[
		"global using global::System;",
		"global using global::System.Buffers;",
		"global using global::ExpressBus.Protocol;",
		"global using global::ExpressBus.Buffering;",
	];

	/// <summary>
	/// Generates serialization members for a single serialization-enabled message type.
	/// </summary>
	/// <remarks>
	/// The partial struct declaration (interfaces, <c>MessageTypeIdentifier</c>)
	/// is generated by <c>MessageGeneration</c>. This method generates:
	/// user properties, <c>ByteSize</c>, constructor,
	/// <c>FromBytes</c>, and <c>ToBytes</c>.
	/// <para>
	/// For <c>[GenerateSerialization]</c> types, it complements <c>MessageGeneration</c>
	/// by adding serialization-specific members.
	/// </para>
	/// </remarks>
	public static string GenerateMembersForSingleType(
		SyntaxSymbol symbol,
		byte identifier,
		Compilation compilation,
		MessageType messageType)
	{
		var semanticModel = compilation.GetSemanticModel(symbol.Declaration.SyntaxTree);
		var props = SerializedPropResolver.ParseSerializedPropAttributes(symbol, semanticModel).ToList();
		var namespaceName = symbol.Symbol.ContainingNamespace.ToDisplayString();
		var typeName = symbol.Symbol.Name;

		var hasMemoryProps = props.Any(p => p.UnderlyingType.IsMemoryType());
		var constantPropSize = ComputeConstantPropSize(props);

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		foreach (var usingDirective in GlobalUsings)
			sb.AppendLine(usingDirective);
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");
		sb.AppendLine($"\tpublic partial struct {typeName} : IByteSerializable<{typeName}>, IMessageSize");
		sb.AppendLine("\t{");

		// User properties — generated from [GenerateSerializedProp] attributes.
		foreach (var prop in props)
			sb.AppendLine($"\t\tpublic {GetPropType(prop)} {prop.Name} {{ get; }}");
		sb.AppendLine();

		// ByteSize — constant if no memory props, runtime-computed otherwise.
		if (hasMemoryProps)
		{
			var constantSize = 1 + constantPropSize;
			var memorySizes = string.Join(" + ", props.Where(p => p.UnderlyingType.IsMemoryType())
				.Select(p => $"{p.Name}.ByteSize"));
			if (constantSize > 0)
				sb.AppendLine($"\tpublic int ByteSize => {constantSize} + {memorySizes};");
			else
				sb.AppendLine($"\tpublic int ByteSize => {memorySizes};");
		}
		else
		{
			sb.AppendLine($"\tpublic int ByteSize => 1 + {constantPropSize};");
		}

		GenerateConstructor(sb, typeName, props);
		GenerateFromBytesMethod(sb, typeName, props, constantPropSize, hasMemoryProps);
		GenerateToBytesMethod(sb, typeName, props);

		sb.AppendLine("\t}");
		sb.AppendLine("}");

		return sb.ToString();
	}

	/// <summary>
	/// Computes the total byte size of all non-memory properties.
	/// </summary>
	private static int ComputeConstantPropSize(IReadOnlyList<MessagePropInfo> props) =>
		props.Where(p => !p.UnderlyingType.IsMemoryType())
			.Sum(p => p.UnderlyingType.ByteSize());

	/// <summary>
	/// Returns the C# type name for a property (enum FQN or primitive/memory type).
	/// </summary>
	private static string GetPropType(MessagePropInfo prop) =>
		prop.EnumType ?? prop.UnderlyingType.CSharpTypeName();

	/// <summary>
	/// Generates the constructor with user-facing parameters.
	/// </summary>
	private static void GenerateConstructor(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props)
	{
		sb.AppendLine();
		var params_ = props.Select(p => $"{GetPropType(p)} {ToCamelCase(p.Name)}");
		sb.AppendLine($"\tpublic {typeName}({string.Join(", ", params_)})");
		sb.AppendLine("\t{");
		foreach (var prop in props)
		{
			var assignment = prop.EnumType is not null
				? $"({prop.EnumType}){ToCamelCase(prop.Name)}"
				: ToCamelCase(prop.Name);
			sb.AppendLine($"\t\t{prop.Name} = {assignment};");
		}
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates the FromBytes deserialization method.
	/// </summary>
	private static void GenerateFromBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props,
		int constantPropSize,
		bool hasMemoryProps)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic static {typeName} FromBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");

		// Validate buffer size before deserialization.
		var minConstantSize = 1 + constantPropSize;
		if (hasMemoryProps)
		{
			if (minConstantSize > 1)
				sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, {minConstantSize}, null);");
		}
		else
		{
			sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, {minConstantSize});");
		}

		sb.AppendLine("\t\tvar reader = new ByteReader(buffer.Span.Slice(1));");
		sb.AppendLine();

		foreach (var prop in props)
		{
			if (prop.UnderlyingType.IsMemoryType())
				GenerateMemoryPropRead(sb, prop);
			else
				GenerateNormalPropRead(sb, prop);
		}

		sb.AppendLine();
		sb.AppendLine($"\t\treturn new {typeName}({string.Join(", ", props.Select(p => ToCamelCase(p.Name)))});");
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates serialization for a non-memory property in FromBytes.
	/// </summary>
	private static void GenerateNormalPropRead(StringBuilder sb, MessagePropInfo prop)
	{
		var readMethod = prop.UnderlyingType.ReadMethodName();
		var paramName = ToCamelCase(prop.Name);
		var varType = GetPropType(prop);
		var cast = prop.EnumType is not null ? $"({varType})" : "";
		sb.AppendLine($"\t\t{varType} {paramName} = {cast}reader.{readMethod}();");
	}

	/// <summary>
	/// Generates serialization for a memory property in FromBytes.
	/// </summary>
	private static void GenerateMemoryPropRead(StringBuilder sb, MessagePropInfo prop)
	{
		var paramName = ToCamelCase(prop.Name);
		var varType = GetPropType(prop);
		var itemSize = prop.UnderlyingType.GetMemoryItemSize();

		sb.AppendLine($"\t\tvar {paramName}Count = reader.ReadInt();");
		sb.AppendLine($"\t\tvar {paramName}ItemSize = reader.ReadByte();");
		sb.AppendLine($"\t\tvar {paramName}Data = reader.ReadBytes({paramName}Count * {paramName}ItemSize).ToArray();");
		sb.AppendLine($"\t\t{varType} {paramName} = new({paramName}Count, {paramName}Data);");
	}

	/// <summary>
	/// Generates the ToBytes serialization method.
	/// </summary>
	private static void GenerateToBytesMethod(
		StringBuilder sb,
		string typeName,
		IReadOnlyList<MessagePropInfo> props)
	{
		sb.AppendLine();
		sb.AppendLine($"\tpublic ReadOnlyMemory<byte> ToBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");
		sb.AppendLine($"\t\tByteTools.EnsureLength(buffer.Span, ByteSize);");
		sb.AppendLine("\t\tvar writer = new ByteWriter(buffer.Span);");
		sb.AppendLine("\t\twriter.WriteByte(MessageTypeIdentifier);");
		sb.AppendLine();

		foreach (var prop in props)
		{
			if (prop.UnderlyingType.IsMemoryType())
				GenerateMemoryPropWrite(sb, prop);
			else
				GenerateNormalPropWrite(sb, prop);
		}

		sb.AppendLine();
		sb.AppendLine("\t\treturn buffer;");
		sb.AppendLine("\t}");
	}

	/// <summary>
	/// Generates serialization for a non-memory property in ToBytes.
	/// </summary>
	private static void GenerateNormalPropWrite(StringBuilder sb, MessagePropInfo prop)
	{
		var writeMethod = prop.UnderlyingType.WriteMethodName();
		var cast = prop.EnumType is not null
			? $"({prop.UnderlyingType.CSharpTypeName()})"
			: "";
		sb.AppendLine($"\t\twriter.{writeMethod}({cast}{prop.Name});");
	}

	/// <summary>
	/// Generates serialization for a memory property in ToBytes.
	/// </summary>
	private static void GenerateMemoryPropWrite(StringBuilder sb, MessagePropInfo prop)
	{
		var propName = prop.Name;
		sb.AppendLine($"\t\tvar {propName}Bytes = new byte[{propName}.ByteSize];");
		sb.AppendLine($"\t\t{propName}.ToBytes({propName}Bytes);");
		sb.AppendLine($"\t\twriter.WriteBytes({propName}Bytes);");
	}

	private static string ToCamelCase(string name) =>
		char.ToLowerInvariant(name[0]) + name.Substring(1);
}
