using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ExpressBus.Protocol.SourceGeneration.Protocol;

/// <summary>
/// Roslyn incremental source generator for protocol message types.
///
/// <para>
/// Finds structs decorated with <c>[Message]</c> and generates the base
/// <c>IMessage</c> implementation (<c>MessageTypeIdentifier</c>, interface
/// declarations) for every such struct.
/// </para>
///
/// <para>
/// For structs that also have <c>[GenerateSerialization]</c>, generates binary
/// serialization members: <c>ByteSize</c>, constructor, <c>FromBytes</c>, and <c>ToBytes</c>.
/// </para>
///
/// <para>
/// Serialization layout (big-endian, no padding):
/// <code>
/// | byte | N bytes...
/// | MessageTypeIdentifier | User fields...
/// </code>
/// </para>
///
/// <para>
/// Attributes are detected via syntax-level string matching rather than semantic
/// resolution because the attributes are generated by this same generator and may
/// not be resolvable during all compilation stages.
/// </para>
/// </summary>
[Generator]
public sealed class ProtocolGenerator : IIncrementalGenerator
{
	private const string CollectMessageTypesTrackingName =
		"ExpressBus.Protocol.SourceGeneration.CollectMessageTypes";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Emit the attribute classes so consuming projects can use them.
		context.RegisterSourceOutput(
			context.CompilationProvider,
			static (ctx, _) =>
			{
				ctx.AddSource("MessageAttributes.g.cs", AttributeGeneration.GenerateAttributeClasses());
			});

		// Collect all message structs ([Message] attribute — includes those with [GenerateSerialization] too).
		var messageTypes = CollectMessageTypes(context);

		var collected = messageTypes
			.Collect()
			.WithTrackingName(CollectMessageTypesTrackingName);

		var combined = context.CompilationProvider.Combine(collected);

		context.RegisterSourceOutput(combined, static (ctx, pair) =>
		{
			var compilation = pair.Left;
			var symbols = pair.Right;

			// Validate all collected types.
			var result = Validation.Validate(symbols, compilation, ctx);

			// Sort serialization types by fully-qualified name for deterministic identifier assignment.
			var sortedSerialization = result.AllValid
				.Where(s => result.SerializationTypeFqns.Contains(s.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
				.OrderBy(s => s.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
				.ToList();

			// Guard: MessageTypeIdentifier is a single byte — max 256 types.
			if (sortedSerialization.Count > byte.MaxValue)
			{
				ctx.ReportDiagnostic(Diagnostic.Create(
					Diagnostics.TooManyMessageTypes,
					sortedSerialization[0].Symbol.Locations[0],
					sortedSerialization.Count,
					byte.MaxValue));
				return;
			}

			// Assign deterministic 0..N-1 identifiers based on sorted FQN for ALL valid types.
			var allSorted = result.AllValid
				.OrderBy(s => s.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
				.ToList();
			var identifierMap = new Dictionary<string, byte>();
			for (int i = 0; i < allSorted.Count; i++)
			{
				var fqn = allSorted[i].Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				identifierMap[fqn] = (byte)i;
			}

			// Emit MessageGeneration for all valid types.
			foreach (var symbol in allSorted)
			{
				var fqn = symbol.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				var id = identifierMap[fqn];
				var isSerializationType = result.SerializationTypeFqns.Contains(fqn);
				var messageType = ResolveMessageType(symbol, compilation);
				var source = MessageGeneration.GenerateMembersForSingleType(symbol, id, compilation, messageType, isSerializationType);
				var typeName = symbol.Symbol.Name;
				ctx.AddSource($"Message_{typeName}.g.cs", source);
			}

			// Emit SerializationGeneration for serialization-enabled types only.
			foreach (var symbol in allSorted)
			{
				var fqn = symbol.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				if (!result.SerializationTypeFqns.Contains(fqn))
					continue;
				var id = identifierMap[fqn];
				var messageType = ResolveMessageType(symbol, compilation);
				var source = SerializationGeneration.GenerateMembersForSingleType(symbol, id, compilation, messageType);
				var typeName = symbol.Symbol.Name;
				ctx.AddSource($"Serialization_{typeName}.g.cs", source);
			}
		});
	}

	/// <summary>
	/// Finds structs with <c>[Message]</c> or <c>[MessageAttribute]</c> via
	/// syntax-level attribute detection (metadata only).
	/// </summary>
	private static IncrementalValuesProvider<SyntaxSymbol> CollectMessageTypes(
		IncrementalGeneratorInitializationContext context)
	{
		return context.SyntaxProvider.CreateSyntaxProvider(
			predicate: static (syntax, _) => syntax is TypeDeclarationSyntax typeDecl
				&& typeDecl.IsKind(SyntaxKind.StructDeclaration)
				&& typeDecl.AttributeLists.Count > 0
				&& typeDecl.AttributeLists.Any(attrList => attrList.Attributes.Any(
					attr => attr.Name.ToString() is "Message" or "MessageAttribute")),
			transform: static (ctx, _) =>
			{
				var typeDecl = (TypeDeclarationSyntax)ctx.Node;

				foreach (var attrList in typeDecl.AttributeLists)
				{
					foreach (var attr in attrList.Attributes)
					{
						var name = attr.Name.ToString();
						if (name == "Message" || name == "MessageAttribute")
						{
							var symbol = ctx.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
							if (symbol is not null)
								return new SyntaxSymbol(typeDecl, symbol);
						}
					}
				}

				return null;
			})
			.WithTrackingName(CollectMessageTypesTrackingName)
			.Where(static s => s is not null)!;
	}

	/// <summary>
	/// Resolves the <see cref="MessageType"/> from the <c>[GenerateSerialization]</c> attribute constructor argument.
	/// </summary>
	private static MessageType ResolveMessageType(SyntaxSymbol symbol, Compilation compilation)
	{
		var semanticModel = compilation.GetSemanticModel(symbol.Declaration.SyntaxTree);
		var genSerialAttrs = symbol.Declaration.AttributeLists
			.SelectMany(list => list.Attributes)
			.Where(attr =>
			{
				var name = attr.Name.ToString();
				return name == "GenerateSerialization" || name == "GenerateSerializationAttribute";
			});

		foreach (var attr in genSerialAttrs)
		{
			var argList = attr.ArgumentList?.Arguments.ToList();
			if (argList == null || argList.Count == 0)
				continue;

			// First argument: MessageType.Request etc.
			var argExpr = argList[0].Expression;
			var typeInfo = semanticModel.GetTypeInfo(argExpr);
			var typeSymbol = typeInfo.Type;
			if (typeSymbol != null && typeSymbol.TypeKind == TypeKind.Enum
				&& typeSymbol.Name == "MessageType")
			{
				if (argExpr is MemberAccessExpressionSyntax memberAccess)
				{
					var memberName = memberAccess.Name.Identifier.Text;
					return memberName switch
					{
						"Request" => MessageType.Request,
						"Response" => MessageType.Response,
						"Notification" => MessageType.Notification,
						"Test" => MessageType.Test,
						_ => throw new InvalidOperationException(
							$"Unknown MessageType value '{memberName}' on '{symbol.Symbol.Name}'."),
					};
				}
			}
		}

		return MessageType.Request;
	}
}
