using Microsoft.CodeAnalysis;
using System.Text;

namespace ExpressBus.Protocol.SourceGeneration.SerializableMemoryGenerator;

/// <summary>
/// Generates concrete SerializableMemory types for binary serialization.
/// </summary>
/// <remarks>
/// Emits 5 structs into the <c>ExpressBus.Protocol</c> namespace:
/// <list type="bullet">
///   <item><description><c>SerializableByteMemory</c> (itemSize=1)</description></item>
///   <item><description><c>SerializableBoolMemory</c> (itemSize=1)</description></item>
///   <item><description><c>SerializableIntMemory</c> (itemSize=4)</description></item>
///   <item><description><c>SerializableLongMemory</c> (itemSize=8)</description></item>
///   <item><description><c>SerializableGuidMemory</c> (itemSize=16)</description></item>
/// </list>
/// <para>
/// Each struct implements <c>IByteSerializable&lt;T&gt;</c> and <c>IMessageSize</c>
/// with a serialization layout: 4 bytes count + 1 byte itemSize + N bytes data.
/// </para>
/// </remarks>
[Generator]
public sealed class SerializableMemoryGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Emit all generated types up-front — these are static, no incremental collection needed.
		foreach (var config in AllowedTypeExtensions.MemoryTypes)
		{
			var source = GenerateSource(config);
			context.RegisterSourceOutput(context.CompilationProvider, (ctx, _) =>
			{
				ctx.AddSource($"{config.TypeName}.g.cs", source);
			});
		}
	}

	private static string GenerateSource(MemoryTypeConfig config)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("global using global::System;");
		sb.AppendLine("global using global::System.Buffers;");
		sb.AppendLine("global using global::ExpressBus.Protocol;");
		sb.AppendLine("global using global::ExpressBus.Protocol.ByteOperations;");
		sb.AppendLine();
		sb.AppendLine("namespace ExpressBus.Protocol;");
		sb.AppendLine();
		sb.AppendLine($"/// <summary>");
		sb.AppendLine($"/// Serializable memory buffer storing <see cref=\"{config.ItemTypeName}\"/> items.");
		sb.AppendLine($"/// </summary>");
		sb.AppendLine($"public readonly partial struct {config.TypeName} : IByteSerializable<{config.TypeName}>, IMessageSize");
		sb.AppendLine("{");

		// Count property.
		sb.AppendLine($"\tpublic readonly int Count {{ get; }}");
		sb.AppendLine();

		// Data property.
		sb.AppendLine($"\tpublic readonly ReadOnlyMemory<byte> Data {{ get; }}");
		sb.AppendLine();

		// Constructor.
		sb.AppendLine($"\t/// <summary>");
		sb.AppendLine($"\t/// Creates a new <see cref=\"{config.TypeName}\"/>.");
		sb.AppendLine($"\t/// </summary>");
		sb.AppendLine($"\t/// <param name=\"count\">The number of items.</param>");
		sb.AppendLine($"\t/// <param name=\"data\">The raw data bytes.</param>");
		sb.AppendLine($"\tpublic {config.TypeName}(int count, ReadOnlyMemory<byte> data)");
		sb.AppendLine("\t{");
		sb.AppendLine($"\t\tCount = count;");
		sb.AppendLine("\t\tData = data;");
		sb.AppendLine("\t}");
		sb.AppendLine();

		// ByteSize property.
		sb.AppendLine($"\tpublic int ByteSize => 5 + Count * {config.ItemSize};");
		sb.AppendLine();

		// FromBytes method.
		sb.AppendLine($"\tpublic static {config.TypeName} FromBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tvar span = buffer.Span;");
		sb.AppendLine($"\t\tByteTools.EnsureLength(span, 5, null);");
		sb.AppendLine("\t\tvar reader = new ByteReader(span);");
		sb.AppendLine("\t\tvar count = reader.ReadInt();");
		sb.AppendLine($"\t\tvar expectedItemSize = reader.ReadByte();");
		sb.AppendLine($"\t\tif (expectedItemSize != {config.ItemSize})");
		sb.AppendLine("\t\t\tthrow new FormatException(");
		sb.AppendLine($"\t\t\t\t$\"Expected item size {config.ItemSize}, got {{expectedItemSize}}.\");");
		sb.AppendLine($"\t\tvar expectedDataSize = 5 + count * {config.ItemSize};");
		sb.AppendLine("\t\tByteTools.EnsureLength(span, expectedDataSize);");
		sb.AppendLine("\t\tvar data = reader.ReadBytes(count * " + config.ItemSize + ").ToArray();");
		sb.AppendLine("\t\treturn new " + config.TypeName + "(count, data);");
		sb.AppendLine("\t}");
		sb.AppendLine();

		// ToBytes method.
		sb.AppendLine($"\tpublic ReadOnlyMemory<byte> ToBytes(Memory<byte> buffer)");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tByteTools.EnsureLength(buffer.Span, ByteSize);");
		sb.AppendLine("\t\tvar writer = new ByteWriter(buffer.Span);");
		sb.AppendLine("\t\twriter.WriteInt(Count);");
		sb.AppendLine($"\t\twriter.WriteByte({config.ItemSize});");
		sb.AppendLine("\t\twriter.WriteBytes(Data.Span);");
		sb.AppendLine("\t\treturn buffer;");
		sb.AppendLine("\t}");

		sb.AppendLine("}");

		return sb.ToString();
	}
}
